# This workflow refreshes the CI cache for Go by download mod dependencies
# and tools.
name: Refresh Go Cache (Export)

on:
  workflow_call:
    inputs:
      runner:
        type: string
        description: The runner to refresh cache for
        default: ubuntu-24.04
      go:
        type: string
        description: The Go version to refresh cache for. If unset, reads from go.work
        default: ""

jobs:
  refresh:
    runs-on: ${{ inputs.runner }}

    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          go-version-file: ${{ !inputs.go && 'go.work' || '' }}
          go-version: ${{ inputs.go }}
          cache: false

      - run: go run ./build download

      - name: resolve environment
        id: goenv
        shell: bash
        run: |
          {
            echo "go_cache=$(go env GOCACHE)"
            echo "go_modcache=$(go env GOMODCACHE)"
            echo "go_version=$(go env GOVERSION)"
          } >> "$GITHUB_OUTPUT"

      - uses: actions/cache/save@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: |
            ${{ steps.goenv.outputs.go_modcache }}
            ${{ steps.goenv.outputs.go_cache }}
          key: go-${{ runner.os }}-${{ steps.goenv.outputs.go_version }}-${{ hashFiles('**/go.mod', '**/versions.go') }}
