# This workflow refreshes the CI cache for Go by download mod dependencies
# and tools.
name: Refresh Go Cache (Export)

on:
  workflow_call:
    inputs:
      runner:
        type: string
        description: The runner to refresh cache for
        default: ubuntu-24.04
      go:
        type: string
        description: The Go version to refresh cache for. If unset, reads from go.work
        default: ""

jobs:
  refresh:
    runs-on: ${{ inputs.runner }}

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version-file: ${{ !inputs.go && 'go.work' || '' }}
          go-version: ${{ inputs.go }}
          cache: false

      - run: go run ./build download

      - name: resolve environment
        id: goenv
        shell: bash
        run: |
          {
            echo "go_cache=$(go env GOCACHE)"
            echo "go_modcache=$(go env GOMODCACHE)"
            echo "go_version=$(go env GOVERSION)"
          } >> "$GITHUB_OUTPUT"

      - uses: actions/cache/save@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5.0.2
        with:
          path: |
            ${{ steps.goenv.outputs.go_modcache }}
            ${{ steps.goenv.outputs.go_cache }}
          key: go-${{ runner.os }}-${{ steps.goenv.outputs.go_version }}-${{ hashFiles('**/go.mod', '**/versions.go') }}
