# This workflow invokes renovate with an app token for creating PRs. It provides
# some global configuration to match go-build's renovate configuration but is
# otherwise quite small and may be better to copy instead of reference.
name: Renovate Dependencies (Export)

on:
  workflow_call:
    inputs:
      github_app_id:
        type: string
        description: ID of GitHub app with contents write permission
        required: true
      debug:
        type: boolean
        description: Whether to enable debug logging
        default: false
    secrets:
      github_app_key:
        description: Private key of GitHub app with contents write permission
        required: true

jobs:
  renovate:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/create-github-app-token@7e473efe3cb98aa54f8d4bac15400b15fad77d94 # v2.2.0
        id: app-token
        with:
          app-id: ${{ inputs.github_app_id }}
          private-key: ${{ secrets.github_app_key }}

      - uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          cache: false

      - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: 24

      - uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2.0.2

      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
        with:
          version: 10

      - run: pnpm --allow-build=re2 dlx renovate@latest
        env:
          RENOVATE_TOKEN: ${{ steps.app-token.outputs.token }}
          RENOVATE_PLATFORM: github
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          RENOVATE_ALLOWED_COMMANDS: "^go work sync$,^go list -m -json | jq '.Dir' | xargs -L1 -I'{}' sh -c 'cd {} && go mod tidy'$"
          LOG_LEVEL: ${{ inputs.debug && 'DEBUG' || 'INFO' }}
